name: Workflow Demo
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting Hello
        run: echo "Hello, this is the first job!"

      - name: Good Bye
        run: echo "This is the first job ending."