name: Workflow Demo
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Full Debug
        run: |
          echo "=== Environment ==="
          pwd
          ls -la
          echo "=== Node/NPM ==="
          node --version
          npm --version
          echo "=== Package.json ==="
          cat package.json || echo "No package.json found"
          echo "=== NPM Config ==="
          npm config list