name: Workflow Demo
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: move repository
      run: cd github-test
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
      
    - name: Install dependencies
      run: npm ci
      
    - name: Install Ionic CLI
      run: npm install -g @ionic/cli
      
    - name: Build Ionic app
      run: ionic build --prod