name: Workflow Demo
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting Hello
        run: |
          cd github-test
          npm run build

      - name: Good Bye
        run: |
          echo "This is the first job ending."
          echo "Goodbye from the first job!"