name: Build Ionic Angular App and Generate APK

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install Ionic CLI
      run: npm install -g @ionic/cli
      
    - name: Install dependencies
      run: npm ci
      
    - name: Build Ionic app
      run: ionic build --prod
      
    - name: Sync Capacitor
      run: ionic capacitor sync android
      
    - name: Build Android APK (unsigned)
      run: |
        cd android
        ./gradlew assembleDebug
    - name: list APK files
      run: ls -la android/app/build/outputs/apk/debug/
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: unsigned-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
  
  build-ios:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Install Ionic CLI
      run: npm install -g @ionic/cli

    - name: Install dependencies
      run: npm ci

    - name: Build Ionic app
      run: ionic build --prod

    - name: Sync Capacitor
      run: ionic capacitor sync ios

    - name: Install CocoaPods
      run: |
        cd ios/App
        pod install

    - name: Install Fastlane
      run: |
        sudo gem install fastlane

    - name: Build iOS app with Fastlane
      run: |
        cd ios/App
        fastlane build

    - name: Upload IPA as artifact
      uses: actions/upload-artifact@v4
      with:
        name: unsigned-ipa
        path: ios/App/fastlane/output/*.ipa
        retention-days: 30